name: PR Test

on:
  pull_request:
    branches: [ develop ]

env:
  WORKING_DIRECTORY: ./backend/server
  
jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 17  
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Build with Gradle
        run: ./gradlew build
        working-directory: ${{ env.WORKING_DIRECTORY }}

      - name: Run tests
        run: ./gradlew test
        working-directory: ${{ env.WORKING_DIRECTORY }}
